#gearman server host(can be multiple)
HOSTS_LIST:
 0.0.0.0:5000

#plugin name(Plug-in must in plugin folder)
PLUGIN_NAME:
 eg

#send jobs cycle time (unit s)
CYCLE:
 0.5

#update job's data time (unit min)
UPDATE:
 1

#debug (0/1/2)
#0:debug is off
#1:print log of run
#2:single-step debugging
DEBUG:
 0
